name: "Build and deploy github to AZ .net"
on: [push, worflow_dispatch]
env:
  AZURE_WEBAPP_NAME: app-win-az
  AZURE_WEBAPP_PACKAGE_PATH: './published'
  NETCORE_VERSION: '3.1.103'
jobs:
  build:
    name:  Build and deploy github to AZ .net
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    - name: Build
      run: dotnet restore
      run: dotnet build --no-restore -c Release
    - name: Publish
      run: dotnet publish --no-build -c Release -o ./published
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_WEBAPP_NAME}}
        publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
        package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}